### ISSUE TITLE
Support elmjutsu (Patreon, PayPal, GitHub Sponsors)

### ISSUE THREAD

**Issue by absynce** [halohalospecial/atom-elm-fu#170]
Hi there!

First I want to thank you for making elmjutsu! I realize it is critical to my Elm development workflow. I have tried the extensions for VS Code and IntelliJ, but they lack a few key features that elmjutsu has. 

The key features for me are all Special Completions. This significantly speeds up my development process and saves me from RSI flare-ups!

Here are some of my favorite ones:
1. Auto-complete case statements and model construction
2. Auto-generate encoders/decoders

With that said, how can I support the great work you've done? I didn't see a way to support you, such as a Patreon, PayPal, or GitHub Sponsors link.

**Comment by halohalospecial** [comment]
Hi @absynce,

Thank you for the very kind words :heart:

I can relate with your RSI issues since I had mild carpal tunnel syndrome before.  That's also part of the reason why I added lots of autocompletions :D  Auto-generation of encoders/decoders seems to be a favorite.  A possible feature in the future is using voice to code haha.

As for supporting the project, submitting issues (bugs, suggestions, etc.) is good enough for me :)

**Comment by absynce** [comment]
Okay, then I will close this, keep an eye out for issues, and share suggestions. 😃 

How are you imagining voice-to-code would work in this case? I tried doing that a bit with Dragon NaturallySpeaking, but it frustrated me.

**Comment by halohalospecial** [comment]
Hi @absynce,

For voice-to-code, I was thinking static typing would help in narrowing down the possible actions each step of the way.  For example, when I say "String.repeat", it would know that the next would most probably be an integer and the ASR would then place higher priorities to int variables in scope or actual integers.  It's also possible to train the ASR with the symbol names from the imported packages.  These are just ideas so I don't know how hard or easy they are to implement haha.

What's frustrating with voice-to-code in your experience?

**Comment by absynce** [comment]
Hi @halohalospecial,

Those sound like useful ideas! A good way to find out how easy they are to implement is to try. 😄 

With Dragon, it was designed more for writing text than code. This made it difficult to use in a code editor to input correct syntax or variables. Even using it for writing email was frustrating, because it seemed to lag, which would distract me, and lead me to make silly mistakes. However, other folks have made it work. I'm excited to see ["Voice Driven Development: Who needs a keyboard anyway?"](https://thestrangeloop.com/2019/voice-driven-development-who-needs-a-keyboard-anyway.html) by Emily Shea at Strange Loop to inspire me to try again.
